# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true # default
contact_links:
  - name: ğŸ“š Documentation
    url: https://brainglobe.info/
    about: Please see here for information about how to install and use BrainGlobe software.
  - name: â“ image.sc forum
    url: https://forum.image.sc/tag/brainglobe
    about: Please ask general questions (e.g. how do I, what is this? etc.) on the image.sc forum. Tagging `brainglobe` and the name of the software (e.g. `cellfinder`).
  - name: ğŸ’¬ Zulip
    url: https://brainglobe.zulipchat.com/
    about: Please join the Zulip chat to ask us any development questions (e.g. how can I contribute?).
